################################################################################
# \file bsp.mk
#
# \brief
# Define the REF_PMG1_B2_DRP target.
#
################################################################################
# \copyright
# Copyright (c) 2026 Infineon Technologies AG
# an affiliate of Infineon Technologies AG
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ifeq ($(WHICHFILE),true)
$(info Processing $(lastword $(MAKEFILE_LIST)))
endif

# Any additional components to apply when using this board.
BSP_COMPONENTS:=

# Any additional defines to apply when using this board.
BSP_DEFINES:=

################################################################################
# ALL ITEMS BELOW THIS POINT ARE AUTO GENERATED BY THE BSP ASSISTANT TOOL.
# DO NOT MODIFY DIRECTLY. CHANGES SHOULD BE MADE THROUGH THE BSP ASSISTANT.
################################################################################

# Board device selection. MPN_LIST tracks what was selected in the BSP Assistant
# All other variables are derived by BSP Assistant based on the MPN_LIST.
MPN_LIST:=CYPM1216-68LQXI
DEVICE:=CYPM1216-68LQXI
DEVICE_COMPONENTS:=CAT2 CCG PMG1B2
DEVICE_CYPM1216-68LQXI_CORES:=CORE_NAME_CM0_0
DEVICE_CYPM1216-68LQXI_DIE:=CCG4PD3
DEVICE_CYPM1216-68LQXI_FLASH_KB:=128
DEVICE_CYPM1216-68LQXI_IPBLOCKS:=CCGFEATURES CCGFEATURES_V1 M0S8CPUSSV2 M0S8CPUSSV2_V1 M0S8IOSS M0S8IOSS_V1 M0S8PERI M0S8PERI_V1 M0S8SCB_VER2 M0S8SCB_VER2_V2 M0S8TCPWM_VER2 M0S8TCPWM_VER2_V2 M0S8USBPD_VER2 M0S8USBPD_VER2_V2 S8SRSSLT S8SRSSLT_V1
DEVICE_CYPM1216-68LQXI_SRAM_KB:=8
DEVICE_LIST:=CYPM1216-68LQXI
DEVICE_TOOL_IDS:=bsp-assistant device-configurator dfuh-tool ez-pd-battery-charger-configurator ez-pd-configurator library-manager lin-configurator project-creator
RECIPE_DIR:=$(SEARCH_recipe-make-cat2)
